### PR TITLE
Greatlte support (first part)

### PR DESCRIPTION
**Pull request by freechelmi**
Created Yaml with right text instructions for greatlte

Yet TODO : create the image for models with Bixby buttons on reboot from download step

Did not test the unlock bootloader

### CODE REVIEW

**Comment by tsterbak** [comment]
Hey, thank you for your contribution! The config looks great so far!

Luckily, Samsung devices don't need the bootloader to be unlocked. At least for all Samsung devices I own, directly booting into download mode and flashing the recovery was fine. Did you have a different experience?

**Comment by freechelmi** [comment]
Yes I think I did it 3 years ago on my greatlte , and for sure on Series10 like galaxy 10e  :+1: 
- From within the Developer options menu, enable OEM unlock.
- hold Volume Down + Bixby and connect USB cable to PC
- Now, click the button that the onscren instructions coorelate to “Continue” and/or “Unlock Bootloader”.

then you have to go through stock Rom to enable adb usb and then the GUI could carry on ..

I guess you could put greatlte on "testing" for now

**Comment by tsterbak** [comment]
Great! I would merge that soon :)

Would you also add the file to the Supported devices section of the README?

**Comment by freechelmi** [comment]
> Great! I would merge that soon :)
> 
> Would you also add the file to the Supported devices section of the README?

Done :-)

**Pull request merged**
