### PR TITLE
Improve the addons installer progress bars and fix issues

### PR DESCRIPTION
**Pull request by tsterbak**
This PR adds:
- Should resolve: #103
- Wait for adb to become available at the right times.

Todo:
- [x] can the device interaction and waiting time be optimized?

### CODE REVIEW

**Comment by MagicLike** [comment]
Will do!

**Comment by MagicLike** [comment]
> @MagicLike If you have time, feel free to test this :)

Ok, I am encountering a weird issue: My OPO gets stuck in the TWRP booting sequence and isn't reachable via CLI anymore...
I will reflash the complete stock firmware and see if that resolves the issue...

**Comment by tsterbak** [comment]
> Ok, I am encountering a weird issue: My OPO gets stuck in the TWRP booting sequence and isn't reachable via CLI anymore...
I will reflash the complete stock firmware and see if that resolves the issue...

Hm, thats weird. :thinking:  is there something odd in the logs?

**Comment by MagicLike** [comment]
> > Ok, I am encountering a weird issue: My OPO gets stuck in the TWRP booting sequence and isn't reachable via CLI anymore...
> > I will reflash the complete stock firmware and see if that resolves the issue...
> 
> Hm, thats weird. thinking is there something odd in the logs?

Nope, nothing... Seems to be related to the device's firmware...

**Pull request merged**
