### PR TITLE
Add new images to GUI

### PR DESCRIPTION
**Pull request by tejasraman**
This PR aims to add new images to OpenAndroidInstaller. PR uses 500x500 files with similar image sizes to previous image sizes. I also have vector files if needed. @tsterbak

### CODE REVIEW

**Comment by MagicLike** [comment]
Would it be possible to add these images as SVGs? That would eliminate scaling issues and reduce file size. see #100

**Comment by tejasraman** [comment]
Please read the original PR; vector images are available. Vector images would be relatively simple to implement, I’ll try to do it

**Comment by tsterbak** [comment]
From my point of view, this would be ready to be merged. But no hurry, if you want to add something it can wait :)
Thanks a lot for the nice visuals!

Actually, the step-indicators are probably also some images that would need attention. If you want to have a look ;)

**Comment by tejasraman** [comment]
> From my point of view, this would be ready to be merged. But no hurry, if you want to add something it can wait :)
> 
> Thanks a lot for the nice visuals!
> 
> 
> 
> Actually, the step-indicators are probably also some images that would need attention. If you want to have a look ;)

I made transparent versions and I want to add slightly higher resolution images.... and add a new steps indicator. I will try to add those today and commit those to my repo

**Comment by tsterbak** [comment]
Hi @tejasraman, did you make any progress on this? Do you need some input from me? :slightly_smiling_face:

**Comment by tejasraman** [comment]
> Hi @tejasraman, did you make any progress on this? Do you need some input from me? :slightly_smiling_face: 

I have made progress and reinstalled my os so it's on my cloud drive now... will upload it soon

**Comment by tsterbak** [comment]
Hey @tejasraman, I'm planning a new release at the end of the month and I would be amazing to ship the upgraded visuals in it :)

If you are busy or so, not an issue. I just wanted to give you a heads up if you want to get the stuff included quickly :)

**Comment by tejasraman** [comment]
> Hey @tejasraman, I'm planning a new release at the end of the month and I would be amazing to ship the upgraded visuals in it :)
> 
> If you are busy or so, not an issue. I just wanted to give you a heads up if you want to get the stuff included quickly :)

I'll finish them and PR them tomorrow, thanks!

**Comment by tsterbak** [comment]
Hey, any news on this? I'm slowing wrapping up the new release and I would really love to have this included :)

**Comment by tejasraman** [comment]
> Hey, any news on this? I'm slowing wrapping up the new release and I would really love to have this included :)

Sorry, I’ve been busy lately.  I’ll do this today, I promise

**Comment by MagicLike** [comment]
@tejasraman A little heads up: the planned release is less than two days away... ^^

**Comment by SirRGB** [comment]
samsung-buttons-bixbi/samsung-buttons text changed in this commit.

Previously it was "press until the screen turns black, then press"
Now it is "press until screen turns black, then press", so the "the" has been purged.

Doesnt sound right to me, but other than that it looks good imo.
It doesnt have to be perfect, you can always pr again.

**Comment by tejasraman** [comment]
> @tejasraman any news on this? There will be another release soonish and I would really love to get this included :)

sorry for being late, I'm doing it right now

**Pull request closed without merging**
