### PR TITLE
Release 0.4.3-beta

### PR DESCRIPTION
**Pull request by tsterbak**
This release adds:
- Support for Samsung Galaxy S4 mini (serranoltexx/serranolte) by @freechelmi 
- Allow Markdown to format text content of device configs (limited markdown set)
- Support for Samsung Galaxy Grand Prime VE (grandprimevelte) by @MagicLike 
- Allow changing the logging location by `poetry run python openandroidinstaller/openandroidinstaller.py -l <logging directory>`
- Support for Samsung Galaxy S8 (dreamlte) by @allaeddineomc 

Improvements:
- Make the Fairphone 2 config clearer
- removed an unneeded reboot instructions for the FPs
- added the TWRP image to every config
- reformatted the configs for more consistency

Fixes:
- A bug where not selecting any add-on leads to a failure of the app. If no add-on is selected, now just reboot to OS at installation time.
- Improve the addons installer progress bars and fix issues
- Try `wipe data` if `format data` fails to enable the use of older TWRP versions
- Improve logging for the run_command function

Todo:
- [x] Bump version numbers
- [x] Update website

### CODE REVIEW

**Comment by tsterbak** [comment]
I tested it with a few devices now and everything seems to work. This will be released in the next days

**Comment by tsterbak** [comment]
> Should I test again with two devices?

That would be great! The more testing the better :)

**Comment by MagicLike** [comment]
> > Should I test again with two devices?
> 
> That would be great! The more testing the better :)

Everything works flawlessly!

**Comment by tsterbak** [comment]
> Everything works flawlessly!

Awesome! Thanks for testing!

**Pull request merged**
