### PR TITLE
Release/0.4.0 beta

### PR DESCRIPTION
**Pull request by tsterbak**
This Release adds:
- install view and allow to circle back to flash a recovery
- enable selecting addons
- enable installing addons
- download buttons for Google apps, f-droid and microg

Improvements:
- typehints
- better views handling 

Fixes:
- remove error messages after retry

### CODE REVIEW

**Comment by tsterbak** [comment]
@SirRGB: If you have some time to spare, it would be great, if you could try this new version with the possibility to flash addons like Gapps, microg or Fdroid. :slightly_smiling_face:

**Comment by SirRGB** [comment]
Sure, will try once I have time...

**Comment by SirRGB** [comment]
https://haste.aicp-rom.com/buzagajaga.sql

Nope

**Comment by tsterbak** [comment]
> https://haste.aicp-rom.com/buzagajaga.sql Nope
> 
> edit: nvm, I was just confused, because you didnt pick the correct OP workaround commit yet...

Stupid me forgot to adapt format changes to the new configs in this PR... Time to run the tests automatically with every commit

**Pull request merged**
