### PR TITLE
a Doc folder to put documentation

### PR DESCRIPTION
**Pull request by Heus-Sueh**
I think it's ok

### CODE REVIEW

**Comment by tsterbak** [comment]
Thanks for reacting so fast :)

Could you also check if there are links pointing to some of the sections or content of it on the website?
https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io
If you want you could open a PR for it (otherwise I can make the changes). (If you do, make sure to include the changes in the templates as well as in the respective public files.)

**Comment by tsterbak** [comment]
Probably a bit pedantic, but could you unify the upper/lowercase of the new files? :sweat_smile:

**Comment by tsterbak** [comment]
Otherwise it looks really good :)

**Comment by Heus-Sueh** [comment]
> Could you also check if there are links pointing to some of the sections or content of it on the website?

I'll check

> Probably a bit pedantic, but could you unify the upper/lowercase of the new files? 😅

ok

**Comment by MagicLike** [comment]
Oh, maybe the [CONTRIBUTING.md](https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/CONTRIBUTING.md) should also be adapted, to link to the detailed docs...

**Comment by Heus-Sueh** [comment]
> Oh, maybe the [CONTRIBUTING.md](https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/CONTRIBUTING.md) should also be adapted, to link to the detailed docs...

it's a good idea but maybe in another PR

**Comment by Heus-Sueh** [comment]
@tsterbak is it ok to merge now?

**Comment by tsterbak** [comment]
> @tsterbak is it ok to merge now?

I want to do it in a calm moment, when I would have time to fix something.

**Pull request merged**
