### PR TITLE
Support for Samsung Galaxy Grand Prime VE

### PR DESCRIPTION
**Pull request by MagicLike**
Added a config for the Samsung Galaxy Grand Prime VE (`grandprimevelte`), but I was not able to test it yet, as the device is not officially supported by LineageOS.

### CODE REVIEW

**Comment by tsterbak** [comment]
Great! :)

You could test with
- https://forum.xda-developers.com/t/lineageos-13-0-for-grand-prime-velte-sm-g531f.3874411/
- https://eu.dl.twrp.me/grandprimevelte/

**Comment by MagicLike** [comment]
> Great! :)
> 
> You could test with
> 
>     * https://forum.xda-developers.com/t/lineageos-13-0-for-grand-prime-velte-sm-g531f.3874411/
> 
>     * https://eu.dl.twrp.me/grandprimevelte/

Hmmm, OAI / adb gets stuck after executing the `adb wait-for-recovery` command in the Install OS view. I already looked at the log and there is nothing suspicious or unusual... TWRP booted completely fine and I can interact with it via touch...
Maybe a timing issue (again)?

**Comment by tsterbak** [comment]
> Hmmm, OAI / adb gets stuck after executing the adb wait-for-recovery command in the Install OS view. I already looked at the log and there is nothing suspicious or unusual... TWRP booted completely fine and I can interact with it via touch...
Maybe a timing issue (again)?

Does the device to `adb wait-for-recovery` (or shows up for `adb devices`) run from the terminal? :thinking:  If not, can you try running `adb kill-server` and `adb start-server` and try again?

**Comment by MagicLike** [comment]
> Does the device to `adb wait-for-recovery` (or shows up for `adb devices`) run from the terminal? thinking If not, can you try running `adb kill-server` and `adb start-server` and try again?

Yes it shows up for `adb devices` and `adb kill-server` gets OAI unstuck, but then it only wipes the cache and userdata partitions and does not install Lineage OS.

Log for install view:
```
2023-04-15 18:34:25.177 | INFO     | views.install_view:build:129 - Starting installation.
2023-04-15 18:34:26.388 | INFO     | views.install_view:check_advanced_switch:63 - Enable advanced output.
2023-04-15 18:34:33.764 | INFO     | tooling:adb_twrp_wipe_and_install:204 - Wipe and format data with twrp, then install os image.
2023-04-15 18:34:33.765 | INFO     | tooling:logging:88 - Wait for recovery - Paramters: {}
2023-04-15 18:34:33.766 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'wait-for-recovery']
2023-04-15 18:34:39.602 | INFO     | tooling:run_command:73 - error: protocol fault (couldn't read status): Success
2023-04-15 18:34:39.604 | ERROR    | tooling:logging:91 - Wait for recovery Failed!
2023-04-15 18:34:39.605 | INFO     | tooling:logging:88 - Perform a factory reset with adb and twrp. - Paramters: {}
2023-04-15 18:34:39.606 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'format', 'data']
2023-04-15 18:34:39.622 | INFO     | tooling:run_command:73 - adb: protocol fault (couldn't read status): Connection reset by peer
2023-04-15 18:34:39.624 | ERROR    | tooling:logging:91 - Perform a factory reset with adb and twrp. Failed!
2023-04-15 18:34:40.626 | INFO     | tooling:logging:88 - Wipe the selected partition with adb and twrp. - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin'), 'partition': 'cache'}
2023-04-15 18:34:40.628 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'wipe', 'cache']
2023-04-15 18:34:40.632 | INFO     | tooling:run_command:73 - * daemon not running; starting now at tcp:5037
2023-04-15 18:34:41.915 | INFO     | tooling:run_command:73 - * daemon started successfully
2023-04-15 18:34:41.916 | INFO     | tooling:run_command:73 - adb: no devices/emulators found
2023-04-15 18:34:41.917 | ERROR    | tooling:logging:91 - Wipe the selected partition with adb and twrp. Failed!
2023-04-15 18:34:42.918 | INFO     | tooling:logging:88 - Wipe the selected partition with adb and twrp. - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin'), 'partition': 'system'}
2023-04-15 18:34:42.920 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'wipe', 'system']
2023-04-15 18:34:42.926 | INFO     | tooling:run_command:73 - adb: no devices/emulators found
2023-04-15 18:34:42.928 | ERROR    | tooling:logging:91 - Wipe the selected partition with adb and twrp. Failed!
2023-04-15 18:34:43.929 | INFO     | tooling:adb_twrp_wipe_and_install:220 - Wiping is done, now activate sideload.
2023-04-15 18:34:43.930 | INFO     | tooling:logging:88 - Activate sideloading in TWRP. - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin')}
2023-04-15 18:34:43.932 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'sideload']
2023-04-15 18:34:44.382 | INFO     | tooling:logging:88 - Wait for sideload - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin')}
2023-04-15 18:34:44.384 | INFO     | tooling:run_command:59 - Run command: ['/*/GitHub/openandroidinstaller/openandroidinstaller/bin/adb', 'wait-for-sideload']
2023-04-15 18:34:45.892 | INFO     | tooling:adb_twrp_wipe_and_install:224 - Sideload and install os image.
2023-04-15 18:34:45.892 | INFO     | tooling:logging:88 - Sideload the target to device with adb. - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin'), 'target': '/*/lineage-13.0-20190515-UNOFFICIAL-FOSS_AUDIO-grandprimevelte.zip'}
2023-04-15 18:34:45.893 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'sideload']
2023-04-15 18:34:45.942 | INFO     | tooling:run_command:73 - 
2023-04-15 18:34:45.943 | INFO     | tooling:run_command:73 - Total xfer: 0.00x
2023-04-15 18:34:52.951 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'wipe', 'dalvik']
2023-04-15 18:34:53.433 | INFO     | tooling:run_command:73 - -- Wiping Dalvik Cache...
2023-04-15 18:34:53.435 | INFO     | tooling:run_command:73 - 
2023-04-15 18:34:53.440 | INFO     | tooling:run_command:73 - Cleaned: /data/dalvik-cache...
2023-04-15 18:34:53.442 | INFO     | tooling:run_command:73 - -- Dalvik Cache Directories Wipe Complete!
2023-04-15 18:34:53.443 | INFO     | tooling:run_command:73 - -- Dalvik Cache Wipe Complete!
2023-04-15 18:34:53.444 | INFO     | tooling:run_command:73 - Done processing script file
2023-04-15 18:34:56.448 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'wipe', 'cache']
2023-04-15 18:34:56.498 | INFO     | tooling:run_command:73 - -- Wiping Cache Partition...
2023-04-15 18:34:56.526 | INFO     | tooling:run_command:73 - Formatting Cache using make_ext4fs function.
2023-04-15 18:34:56.923 | INFO     | tooling:run_command:73 - -- Cache Partition Wipe Complete!
2023-04-15 18:34:56.925 | INFO     | tooling:run_command:73 - Done processing script file
2023-04-15 18:35:06.935 | INFO     | tooling:logging:88 - Rebooting device with adb. - Paramters: {'bin_path': PosixPath('/*/openandroidinstaller/openandroidinstaller/bin')}
2023-04-15 18:35:06.937 | INFO     | tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'reboot']
2023-04-15 18:35:14.870 | SUCCESS  | views.install_view:run_install:213 - Installation process was successful. Allow to continue.
2023-04-15 18:38:25.176 | INFO     | __main__:to_next_view:184 - Confirmed and moved to next step.
2023-04-15 18:38:26.314 | SUCCESS  | views.success_view:close_window:39 - Success! Close the window.
```

**Comment by tsterbak** [comment]
> Yes it shows up for adb devices and adb kill-server gets OAI unstuck, but then it only wipes the cache and userdata partitions and does not install Lineage OS.

Curious issue... :thinking:  I had something similar after trying too many things with adb and fastboot. I was already worried my device/usb-ports/cables are broken, but a PC system reboot fixed that issue. That also seems to be a solution for some people with this issue online (for example XDA).

**Comment by MagicLike** [comment]
> > Yes it shows up for adb devices and adb kill-server gets OAI unstuck, but then it only wipes the cache and userdata partitions and does not install Lineage OS.
> 
> Curious issue... thinking I had something similar after trying too many things with adb and fastboot. I was already worried my device/usb-ports/cables are broken, but a PC system reboot fixed that issue. That also seems to be a solution for some people with this issue online (for example XDA).

I will try a reboot later and maybe switching the port...

**Comment by MagicLike** [comment]
> > > Yes it shows up for adb devices and adb kill-server gets OAI unstuck, but then it only wipes the cache and userdata partitions and does not install Lineage OS.
> > 
> > 
> > Curious issue... thinking I had something similar after trying too many things with adb and fastboot. I was already worried my device/usb-ports/cables are broken, but a PC system reboot fixed that issue. That also seems to be a solution for some people with this issue online (for example XDA).
> 
> I will try a reboot later and maybe switching the port...

Ok, I tried it - nothing changes...

**Comment by MagicLike** [comment]
Ohhh I think I know why it fails - TWRP 2.8.7.0 does not know e.g. the command `format`, etc.

**Comment by MagicLike** [comment]
Also another thing I have spotted: When booting into recovery and the Samsung logo is shown, there is a red Message on to which says `Recovery is not Seandroid enforcing`.

**Comment by MagicLike** [comment]
I acquired a newer unofficial version of TWRP, but OAI won't let me flash it. Is there an option to bypass this block?

**Comment by tsterbak** [comment]
> I acquired a newer unofficial version of TWRP, but OAI won't let me flash it. Is there an option to bypass this block?
Or maybe make an exception for this particular file...

The very basic check on the recovery compatibility with the device is performed by looking for the device code and "twrp" in the file name. So if your TWRP image follows this convention it should let it flash it.

**Comment by MagicLike** [comment]
> > I acquired a newer unofficial version of TWRP, but OAI won't let me flash it. Is there an option to bypass this block?
> > Or maybe make an exception for this particular file...
> 
> The very basic check on the recovery compatibility with the device is performed by looking for the device code and "twrp" in the file name. So if your TWRP image follows this convention it should let it flash it.

Ok, that worked, but `adb shell twrp format data` does still not get recognised by TWRP 3.1.1.0 (The unofficial version I found on XDA)... Would it be possible to make an exception when this device is detected to execute `adb shell twrp wipe data` instead of the format command? Or is there something else I could do?

**Comment by MagicLike** [comment]
@tsterbak Is there a variable in which the current device is stored?

**Comment by tsterbak** [comment]
> Ok, that worked, but adb shell twrp format data does still not get recognised by TWRP 3.1.1.0 (The unofficial version I found on XDA)... Would it be possible to make an exception when this device is detected to execute adb shell twrp wipe data instead of the format command? Or is there something else I could do?

You could try to replace `format data` by `wipe data` in this function here (https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/dev/openandroidinstaller/tooling.py#L181) and test if it works. If it does, I can probably put that in properly.

**Comment by tsterbak** [comment]
> @tsterbak Is there a variable in which the current device is stored?

In the views you can access it by `self.state.config.device_code`.

**Comment by tsterbak** [comment]
Maybe, there should be a warning somewhere in general, that there might be issues with old twrp versions possibly not supporting all features.

**Comment by MagicLike** [comment]
> > Ok, that worked, but adb shell twrp format data does still not get recognised by TWRP 3.1.1.0 (The unofficial version I found on XDA)... Would it be possible to make an exception when this device is detected to execute adb shell twrp wipe data instead of the format command? Or is there something else I could do?
> 
> You could try to replace `format data` by `wipe data` in this function here (https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/dev/openandroidinstaller/tooling.py#L181) and test if it works. If it does, I can probably put that in properly.

Ok, yeah with wipe instead of format it totally works... No errors so far.

**Comment by MagicLike** [comment]
> If it does, I can probably put that in properly.

I tried to do it myself, but I only get `NameError: name 'self' is not defined`... ^^

My changes:
```
def __init__(self):
    self.state.config.device_code = device_code
```

```
    if self.state.config.device_code==grandprimevelte: 
        for line in run_command("adb shell twrp wipe data", bin_path):
            yield line
    else:
        for line in run_command("adb shell twrp format data", bin_path):
            yield line
```

**Comment by tsterbak** [comment]
```python
def __init__(self):
      self.state.config.device_code = device_code
```
Is not necessary, and I also don't know where this function is going?


```python
    if self.state.config.device_code==grandprimevelte: 
        for line in run_command("adb shell twrp wipe data", bin_path):
            yield line
    else:
        for line in run_command("adb shell twrp format data", bin_path):
            yield line
```
I assume this is in the tooling module. There you have no access to the components of the views and the state since I try to keep the direct device interactions as separate from the rest as I could manage. 
What you could try, is to pass a `use_wipe` boolean flag to the function to trigger this change.
Or, just let the `format` fail, catch that and retry with `wipe data`. If this doesn't break adb, I think I would prefer this.

**Comment by MagicLike** [comment]
> ```python
> def __init__(self):
>       self.state.config.device_code = device_code
> ```
> Is not necessary, and I also don't know where this function is going?
> 
> 
> ```python
>     if self.state.config.device_code==grandprimevelte: 
>         for line in run_command("adb shell twrp wipe data", bin_path):
>             yield line
>     else:
>         for line in run_command("adb shell twrp format data", bin_path):
>             yield line
> ```
> I assume this is in the tooling module. There you have no access to the components of the views and the state since I try to keep the direct device interactions as separate from the rest as I could manage. 
> What you could try, is to pass a `use_wipe` boolean flag to the function to trigger this change.
> Or, just let the `format` fail, catch that and retry with `wipe data`. If this doesn't break adb, I think I would prefer this.

Uhhhhhm I must also say, that I am a total beginner in python and only hack myself around things... If it would be possible, please make the changes yourself. I am also not really available for coding until next Sunday so yeah...

**Comment by MagicLike** [comment]
I will try it myself now once...

**Comment by MagicLike** [comment]
@tsterbak Ok, I am not really getting anywhere...
I tried to do it using try and except, but it won't really work:

```python
    try:
        for line in run_command("adb shell twrp format data", bin_path):
            yield line
    except:
        print("Data partition can not be formatted, attempting to wipe it.")
        for line in run_command("adb shell twrp wipe data", bin_path):
            yield line
```

**Comment by tsterbak** [comment]
Hey @MagicLike, I implemented a small change where, if `format data` fails it is retried with `wipe data`. You can see the PR here: #142. Give it a try if you find time :) Hopefully that solves this issue.

**Comment by MagicLike** [comment]
> Hey @MagicLike, I implemented a small change where, if `format data` fails it is retried with `wipe data`. You can see the PR here: #142. Give it a try if you find time :) Hopefully that solves this issue.

I am gonna try it out rn!

**Comment by MagicLike** [comment]
@tsterbak Ok, I tested it yesterday multiple times and the log does not show any indication, that there was a retry with `wipe data`...

**Comment by tsterbak** [comment]
> @tsterbak Ok, I tested it yesterday multiple times and the log does not show any indication, that there was a retry with wipe data...
Did you get the code from #142 to this branch before testing?

**Comment by MagicLike** [comment]
> > @tsterbak Ok, I tested it yesterday multiple times and the log does not show any indication, that there was a retry with wipe data...
> 
> Did you get the code from #142 to this branch before testing?

Jup, just copied the contents of tooling and pasted it into my local file...

**Comment by tsterbak** [comment]
> Jup, just copied the contents of tooling and pasted it into my local file...

Hm, curious... :thinking: 
Does it show soemthing like `tooling:run_command:59 - Run command: ['/*/openandroidinstaller/openandroidinstaller/bin/adb', 'shell', 'twrp', 'wipe', 'data']` at any point in the logfile?

**Comment by MagicLike** [comment]
> > Jup, just copied the contents of tooling and pasted it into my local file...
> 
> Ah wait! I made a mistake... I'll fix the code in the other branch now.

Hmmm, the behaviour is still the same...  `data` is not wiped.

**Comment by MagicLike** [comment]
> > Hmmm, the behaviour is still the same... data is not wiped.
> 
> Thanks for testing again. It's a bit hard to tell what is happening... thinking Is there something new in the logs?

Sadly not...

**Comment by tsterbak** [comment]
> Sadly not...

Hm, that's a pity. So hard to tell what is going on...
From the above logs, it also looks like the adb already fails at "wait-for-recovery". Is there a way to know if the device's adb version already supports that?

**Comment by MagicLike** [comment]
> > Sadly not...
> 
> Hm, that's a pity. So hard to tell what is going on...
> From the above logs, it also looks like the adb already fails at "wait-for-recovery". Is there a way to know if the device's adb version already supports that? 

I actually don't know, but I tried to run the command seperately and it returns no error...

**Comment by tsterbak** [comment]
Did it work now?

**Comment by MagicLike** [comment]
> Did it work now?

Not quite - I am gonna do another test on a fresh codebase directly pulled from main and insert the config and tooling changes. Lets see...

**Comment by tsterbak** [comment]
> Not quite - I am gonna do another test on a fresh codebase directly pulled from main and insert the config and tooling changes. Lets see...

We'll, let's see. Otherwise I have to find a way to iterate on this faster to figure out what is going wrong and how to fix it...

**Comment by MagicLike** [comment]
> > Not quite - I am gonna do another test on a fresh codebase directly pulled from main and insert the config and tooling changes. Lets see...
> 
> We'll, let's see. Otherwise I have to find a way to iterate on this faster to figure out what is going wrong and how to fix it...

Here is the complete log - it still does not seem to do anything with the data partition. Maybe make it standard to first wipe it and - if supported - format it?

[openandroidinstaller.log](https://github.com/openandroidinstaller-dev/openandroidinstaller/files/11412069/openandroidinstaller.log)

**Comment by MagicLike** [comment]
> Maybe make it standard to first wipe it and - if supported - format it?

I guess that would be a good option... (?)

**Comment by tsterbak** [comment]
> I guess that would be a good option... (?)

I'm a bit reluctant to change the current command sequence since it has been tested with a lot of devices. But maybe this is the way to go.

I gave it another try and make it explicitly fail if the command is unknown. And then resolve that by retrying. Hopefully this works...

**Comment by tsterbak** [comment]
> Uhhhhmmmm

Ahhh, stupid mistake... Sorry for wasting your time...

**Comment by tsterbak** [comment]
Should be fixed now.

**Comment by MagicLike** [comment]
> > Uhhhhmmmm
> 
> Ahhh, stupid mistake... Sorry for wasting your time...

No problem, without me "wasting" time, the issue wouldn't have been discovered 😁

**Comment by MagicLike** [comment]
> Should be fixed now.

Gonna test it out later today!

**Comment by MagicLike** [comment]
I will just test it out with the older TWRP (the official version), to verify that it also works with that!

So please wait with merging both PRs!

**Comment by MagicLike** [comment]
@tsterbak Uhhhhh this happens, when I want to click continue after installing:

```
Exception in thread Thread-120:
Traceback (most recent call last):
  File "/*/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/*/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/*/openandroidinstaller/openandroidinstaller/openandroidinstaller.py", line 185, in to_next_view
    self.view.update()
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/control.py", line 259, in update
    self.__page.update(self)
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/page.py", line 221, in update
    added_controls = self.__update(*controls)
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/page.py", line 231, in __update
    control.build_update_commands(self._index, added_controls, commands)
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/control.py", line 328, in build_update_commands
    innerCmds = ctrl._build_add_commands(
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/control.py", line 381, in _build_add_commands
    self._build()
  File "/*/.cache/pypoetry/virtualenvs/openandroidinstaller-2qNGYNIQ-py3.9/lib/python3.9/site-packages/flet/user_control.py", line 12, in _build
    content = self.build()
  File "/*/openandroidinstaller/openandroidinstaller/views/success_view.py", line 54, in build
    Markdown(
  File "/*/openandroidinstaller/openandroidinstaller/styles.py", line 30, in __init__
    super().__init__(
TypeError: flet.markdown.Markdown.__init__() got multiple values for keyword argument 'on_tap_link'
```

**Comment by tsterbak** [comment]
> @tsterbak Uhhhhh this happens, when I want to click continue after installing:

Oh, I see... It should be fixed now :)

**Comment by MagicLike** [comment]
> > @tsterbak Uhhhhh this happens, when I want to click continue after installing:
> 
> Oh, I see... It should be fixed now :)

Everything works, flashing is fine - ready to merge! :smiley:

**Pull request merged**
