### PR TITLE
Add support for jasmine_sprout (Mi A2 / 6X)

### PR DESCRIPTION
**Pull request by anon1892**
Related to #367
Same README order as #392 (but without lancelot, I hope there won't be a mess when we merge...)

@Blackcougar-ita, could you test it please? We can help you if needed

### CODE REVIEW

**Comment by tsterbak** [comment]
What's the reason for the partition retrofitting note? Is this commonly done for that device?

**Comment by anon1892** [comment]
To be honest, I don't understand everything around retrofit partitions, and it seems to require some additional steps / special recovery... For now, I prefer to support this phone only with “standard” ROMs, and I will look dipper on retrofit partitions when I will have more time. (This applies to some others phones too)

Yes, I see several ROMs for this phone with retrofit partitions, so I write this note just to be sure...

**Comment by tsterbak** [comment]
The installation instructions for lineageos 18 don't mention any need for retrofitting: https://wiki.lineageos.org/devices/jasmine_sprout/install/#
Are there more recent roms for this device that might need it?

**Comment by tsterbak** [comment]
Looks good to go. Should I merge it?

**Comment by anon1892** [comment]
Yep, I think it's good

**Pull request merged**
