### PR TITLE
add microg installer revived

### PR DESCRIPTION
**Pull request by SirRGB**
* MinMicroG hasnt been updated for over a year.

### CODE REVIEW

**Comment by tsterbak** [comment]
Thank you for the suggestion. I'll test the microg version and then merge this :)

**Comment by MagicLike** [comment]
Isn't there another way to install microG via TWRP?

**Comment by MagicLike** [comment]
Got an idea: what if we would build MinMicroG ourselves?

**Comment by tsterbak** [comment]
> Isn't there another way to install microG via TWRP?

There is, as recommend currently in the application. But the source I recommend is not very up-to-date so a new source for the same way would be nice.

**Comment by MagicLike** [comment]
> > Isn't there another way to install microG via TWRP?
> 
> There is, as recommend currently in the application. But the source I recommend is not very up-to-date so a new source for the same way would be nice.

As I already mentioned - we could potentially build MinMicroG ourselves and offer a download. I will try and see if I get newer packages or just the same that are already offered to download...

**Comment by dumblob** [comment]
@MagicLike maybe setup a CI in this repo with this: https://gitlab.com/2tefan-projects/android/rom-builder in case upstream devs do not provide the images any more?

**Comment by MagicLike** [comment]
@tsterbak @SirRGB @dumblob 

I found builds from the same Account which are checked daily for updates! (I also build MinMicroG myself and they are the exact same files - or at least have the same size)

The releases can be found here: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases

**Comment by tsterbak** [comment]
> The releases can be found here: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases

That looks good, maybe we can point users to these releases. Looks reasonably up-to-date and regularly rebuild.

**Comment by MagicLike** [comment]
> Looks reasonably up-to-date and regularly rebuild.

Jeah, the CI checks every 24 hours if a new Version of any dependencies is available and if so rebuilds...

**Comment by MagicLike** [comment]
Just tested it, works fine! (at least for myself)

**Comment by SirRGB** [comment]
Nice, didnt know this existed👍

**Comment by tsterbak** [comment]
I guess this is closed with #136. Otherwise please reopen :)

**Pull request closed without merging**
