### PR TITLE
Release/0.3.5 alpha

### PR DESCRIPTION
**Pull request by tsterbak**
This release adds:

Support for new devices:
* Motorola moto z (griffin) (thanks to @SirRGB)
* OnePlus 5 (cheeseburger) (thanks to @SirRGB)
* OnePlus 5T (dumpling) (thanks to @SirRGB)
* Samsung Galaxy S III Neo (s3ve3g)

### CODE REVIEW

**Comment by SirRGB** [comment]
https://github.com/openandroidinstaller-dev/openandroidinstaller#officially-supported-devices

Forgot to bump the device count...

**Comment by tsterbak** [comment]
> https://github.com/openandroidinstaller-dev/openandroidinstaller#officially-supported-devices
> 
> I forgot to bump the device count...

I will go through it all before the release :) Also I'll update the stuff on the website with regards to the new devices. The automation is not in place yet :D

**Comment by SirRGB** [comment]
grafik
Weirdly it didnt work this time.
Worked when flashing crdroid 6 over RR and back, but using nusantara it just isnt recognized. The janky solution is to just make two files ig. Or does your mapping accommodate for both names?

**Comment by tsterbak** [comment]
Thanks for testing that again!
Ah yes, sometimes custom ROMs change the exposed device code... Even LineageOS does that sometimes.
I applied the same "hack" now as I used for the other OnePlus devices. It should work now.

**Comment by SirRGB** [comment]
Didnt u forget something in ur last commit? Shouldnt the config be moved instead of deleted? Or id I misunderstand something?

**Comment by tsterbak** [comment]
You are right :see_no_evil:

**Comment by tsterbak** [comment]
This should be solved now. I added the renamed files.

**Pull request merged**
