### PR TITLE
Add support for cupid (Xiaomi 12)

### PR DESCRIPTION
**Pull request by anon1892**
Asked here : #285 

This device configuration file is not tested. (but should be working, LineageOS installation process is the same as #226, and so the device configuration file is)

Maybe @RedAuburn want to test it?

### CODE REVIEW

**Comment by RedAuburn** [comment]
woah that was fast! i'll be happy to test it once my bootloader is unlocked :)

**Comment by MagicLike** [comment]
The configs state they are for the Xiaomi 12, but the PR is titled Xiaomi 13 - what is the correct one @anon1892?

**Comment by anon1892** [comment]
`cupid` is Xiaomi 12: https://forum.xda-developers.com/f/xiaomi-12.12491/

Xiaomi 13 is `fuxi` : https://forum.xda-developers.com/f/xiaomi-13.12681/

**Comment by MagicLike** [comment]
@RedAuburn Did you have the chance to test the config?

**Comment by RedAuburn** [comment]
still waiting for my bootloader to unlock :( it'll unlock in the evening of the 30th

**Comment by MagicLike** [comment]
> still waiting for my bootloader to unlock :( it'll unlock in the evening of the 30th

Any updates on your bootloader?

**Pull request merged**
