### PR TITLE
Handle zip related exceptions

### PR DESCRIPTION
**Pull request by anon1892**
Related to #416, but don't explain it.
This PR just handle a system image as invalid instead of crashing when : 
- File is not a zip file (so like #416 )
- File is a zip file but does not contain metadata file

For now, only `IMG-e-1.18-t-20231207360613-stable-FP5.zip` is known to be in the second case, and it's a very strange installation package, OAI cannot handle that for now (related to #288 ?), so the file is shown as invalid.
Maybe we can explain it with more details to the user?

### CODE REVIEW

**Comment by tsterbak** [comment]
Nice! I updated the branch to be in sync with the refactoring of the logic of image validation and error messages. Can you have a quick look again, if this is in your sense. Then I merge it  :)

**Comment by anon1892** [comment]
Uh, your commit broke it. I will investigate.

**Comment by tsterbak** [comment]
> Uh, your commit broke it. I will investigate.

Ah sorry, I guess I know what went wrong... it should return `dict()` and not `dict`. I missed to add this correctly...

**Comment by anon1892** [comment]
I looked at it. The problem comes from the fact that the first instruction of `image_works_with_device()` is calling `retrieve_image_metadata()` : it tries to find metadata, then fails in the case it's not a zip file.
It's written in the logs, but there is no way to send this information to the first called function : then, the showed message is the same as a file without metadata (because the second function only send an empty dictionary)... But it shouldn't.

How do we handle that?

**Comment by tsterbak** [comment]
I tried to handle it, now it should work smoothly.

Let me know what you think :)

**Comment by anon1892** [comment]
Yes, it works, !

**Pull request merged**
