### PR TITLE
Support for OnePlus One

### PR DESCRIPTION
**Pull request by MagicLike**
Added a config for OnePlus One (`bacon`), based on the OnePlus 5 config by @SirRGB. But it is still untested... (Hopefully I have the time to test it in the next few days / week(s))

### CODE REVIEW

**Comment by MagicLike** [comment]
@tsterbak I needed to add two config because of a change of the device code after install... (see https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/98/commits/4b616abd35badedab80638ca51da8222d80b5646)

**Comment by tsterbak** [comment]
Looks good! It will be included in the next release! :slightly_smiling_face: Thanks a lot! 

> @tsterbak I needed to add two config because of a change of the device code after install... (see https://github.com/openandroidinstaller-dev/openandroidinstaller/commit/4b616abd35badedab80638ca51da8222d80b5646)

Yeah, this is currently a limitation. The detected code directly maps to the config files one-to-one, which is apparently an issue for  some OnePlus devices (and also some Sony as far as I know). I'll try to address that in the next release by putting a list of device codes working with a config directly to the file. But it's perfectly fine as you did it now. :slightly_smiling_face:

**Comment by MagicLike** [comment]
I got another weir issue: when I try to flash the recovery and open it, OAI / `adb wait-for-recovery` just gets stuck. But if I reboot into recovery manually it works perfectly fine and boots twrp... Where could be the issue?

**Comment by tsterbak** [comment]
> I got a weird issue: when I try to flash the recovery and open it, OAI / adb wait-for-recovery just gets stuck. But if I reboot into recovery manually it works perfectly fine and boots twrp... Where could be the issue?

Thats odd :thinking: Do you mean it doesn't boot TWRP or that it doesn't continue once it's booted and hangs at adb wait-for-recovery? Can you attach the log file for that run?

**Comment by MagicLike** [comment]
> > I got a weird issue: when I try to flash the recovery and open it, OAI / adb wait-for-recovery just gets stuck. But if I reboot into recovery manually it works perfectly fine and boots twrp... Where could be the issue?
> 
> Thats odd thinking Do you mean it doesn't boot TWRP or that it doesn't continue once it's booted and hangs at adb wait-for-recovery? Can you attach the log file for that run?

Where is it saved? Or should I just copy the terminal output?

**Comment by tsterbak** [comment]
> Where is it saved? Or should I just copy the terminal output?

It's created in the same directory where you run the executable.

**Comment by MagicLike** [comment]
> > Where is it saved? Or should I just copy the terminal output?
> 
> It's created in the same directory where you run the executable.

[openandroidinstaller.log](https://github.com/openandroidinstaller-dev/openandroidinstaller/files/10949652/openandroidinstaller.log)

(I replaced the paths with a `*`)

**Comment by tsterbak** [comment]
Thank you :)  It looks like everything worked fine :thinking: Does TWRP boot up at all? Sometimes it might be necessary to swipe right to make the recovery available for adb.

**Comment by MagicLike** [comment]
> Thank you :) It looks like everything worked fine thinking Does TWRP boot up at all? Sometimes it might be necessary to swipe right to make the recovery available for adb.

Nope, it stays in fastboot mode... But if I run `adb reboot recover` TWRP boots up normally.

**Comment by MagicLike** [comment]
Could it be a problem, that the same TWRP version I try to flash is already flashed?

**Comment by MagicLike** [comment]
> Could it be a problem, that the same TWRP version I try to flash is already flashed?

Nope, it does not change anything and a magisk patched boot partition does not take a effect on it... (based on my testing)

**Comment by tsterbak** [comment]
Hm, interesting. Looks like it doesn't boot into recovery by itself. Does it work when you press the hardware buttons like described under "Installing a custom recovery" step 6 here? https://wiki.lineageos.org/devices/bacon/install

**Comment by MagicLike** [comment]
> Hm, interesting. Looks like it doesn't boot into recovery by itself. Does it work in OAI when you press the hardware buttons like described under "Installing a custom recovery" step 6 here? https://wiki.lineageos.org/devices/bacon/install

Kinda, when I reboot into Recovery while it hangs on `adb wait-for-recovery` it runs `fastboot reboot recovery` and then says `< waiting for any device >`. Even if I reboot twice into recovery, nothing happens...

**Comment by MagicLike** [comment]
Even if I go into fastboot manually and type `fastboot reboot recovery` it just boots into the normal system...

**Comment by MagicLike** [comment]
OAI eventually accepted it, but after multiple reboots from fastboot, twrp and adb... (I think the problem is, that from fastboot it won't boot into recovery rn, but I can't imagine why)

**Comment by MagicLike** [comment]
If I then click continue it throws an error;
```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```

**Comment by tsterbak** [comment]
Hm, might actually be an issue in my code which leads to waiting for recovery to early. I will not be able to work on it since I'm travelling for the next two weeks, but then it will be high priority. If you are running the development version with python, you could try to remove line 375 and 376 in tooling.py and see if that helps.

**Comment by MagicLike** [comment]
> Hm, might actually be an issue in my code which leads to waiting for recovery to early. I will not be able to work on it since I'm travelling for the next two weeks, but then it will be high priority. If you are running the development version with python, you could try to remove line 375 and 376 in tooling.py and see if that helps.

Ok, that fixed one of the issues, but my device apparently does not boot into recovery when `fastboot reboot recovery` is executed, it just boots into the normal system...

**Comment by MagicLike** [comment]
If nothing helps, I will try to lock and unlock the bootloader again, so the device completely reformats. Then I will try again...

**Comment by tsterbak** [comment]
Hm, that might indicate, that TWRP wasn't flashed successfully or the TWRP image has issues. A thing that helps quite often is to try a different usb-cable and usb-port, as well as a different TWRP version if you have one available. But that might not help here, since you already got it working without OAI, right? :thinking:

**Comment by MagicLike** [comment]
> Hm, that might indicate, that TWRP wasn't flashed successfully or the TWRP image has issues. A thing that helps quite often is to try a different usb-cable and usb-port, as well as a different TWRP version if you have one available. 

I don't think, that that could be the issue - it worked before...

>But that might not help here, since you already got it working without OAI, right?

Yup, when I do it manually it works fine... Maybe my boot partition is borked...

**Comment by MagicLike** [comment]
> Maybe my boot partition is borked...

Nope, not the problem...

**Comment by MagicLike** [comment]
Ok uhm, I got another (maybe) weird behavior: Every time the system boots now, it says "Auf Werkseinstellung zurücksetzen" and reboots into reovery, but actually does not do anything...

**Comment by MagicLike** [comment]
Somehow I got OAI to reinstall lineage OS now... Lets see if it helps.

**Comment by MagicLike** [comment]
When I re-unlock the bootloader with the lineage recovery, it throws an error `E: Invalid command argument`

**Comment by MagicLike** [comment]
I will just try and make a complete reformat of `/system`, `/cache` and `/data`...

**Comment by MagicLike** [comment]
@tsterbak My guess is, that the bootloader of the OnePlus One uses old commands, which do not get recognized by the lineage recovery nor by TWRP... I will add a notice to the config... (It worked with the stock recovery, so bootloader is able to communicate with it. But the stock recovery image is no longer available...)

**Comment by tsterbak** [comment]
Thank you for all the things you tried and your suggestions in the issues! :) some of the things will be added to the next release when I'm back from travelling.
Then I'll also be able to investigate this issue further and see if there is a solution for it. For the start, adding the notice like you did should suffice.

BTW, can you boot TWRP directly without flashing it with `fastboot boot TWRP.img`? Then this could be a shortcut solution.

Either way, thanks a lot :)

**Comment by MagicLike** [comment]
> BTW, can you boot TWRP directly without flashing it with `fastboot boot TWRP.img`? Then this could be a shortcut solution.

Yes I can - maybe that would be a general better solution to just boot TWRP instead of overwriting the stock recovery... (That would fix the issue with the bootloader not being able to communicate with the recovery)

**Comment by tsterbak** [comment]
Great! You could test that with OAI by changing the command in line 372 in tooling.py to `fastboot boot`. Would be easy to add an alternative function for it, or maybe it should be done like this all the time, like for a/b-partitioned devices.

**Comment by MagicLike** [comment]
> Great! You could test that with OAI by changing the command in line 372 in tooling.py to `fastboot boot`. Would be easy to add an alternative function for it, or maybe it should be done like this all the time, like for a/b-partitioned devices.

I modified the code a bit more and it works like a charm! Should I also implement that it is done always - regardless how it is formatted and open a PR?

Also what is a/b-partitioning? 😅

**Comment by MagicLike** [comment]
> > BTW, can you boot TWRP directly without flashing it with `fastboot boot TWRP.img`? Then this could be a shortcut solution.
> 
> Yes I can - maybe that would be a general better solution to just boot TWRP instead of overwriting the stock recovery... (That would fix the issue with the bootloader not being able to communicate with the recovery)

I just tested it with stock recovery and new OS - worked completely fine, now the data wipe after `fastboot oem unlock` works too! :tada:

**Review by tsterbak — APPROVED** [review]

**Pull request merged**
