### PR TITLE
Add support for Pixel 6a (bluejay)

### PR DESCRIPTION
**Pull request by tejasraman**
Adds configuration file for Pixel 6a (bluejay). Process for unlocking BL is extremely similar to that of the Pixel 5a (barbet). 

I set the required Android version to 13.0.0 (as firmware was changed for Tensor-based devices with A13). Config files for 6a should also work with 6 and 6 pro (if modified).

Tested and working here @tsterbak

### CODE REVIEW

**Comment by tsterbak** [comment]
Hey, thanks a lot for the contribution! :relaxed: 
It will be part of the next release.

So it seems this part (https://wiki.lineageos.org/devices/bluejay/install#flashing-additional-partitions) isn't required if you use TWRP? I was not sure about this yet, but it would open up support for some more devices.

**Comment by tejasraman** [comment]
> Hey, thanks a lot for the contribution! ☺️ It will be part of the next release.
> 
> So it seems this part (https://wiki.lineageos.org/devices/bluejay/install#flashing-additional-partitions) isn't required if you use TWRP? I was not sure about this yet, but it would open up support for some more devices.

So afaik there is no twrp for the 6 series (and instead lineage recovery needs to be flashed) - so that step is required.

**Comment by tsterbak** [comment]
This TWRP worked for me: https://forum.xda-developers.com/t/recovery-unofficial-twrp-for-barbet.4387057/

**Comment by tejasraman** [comment]
That makes sense, but it seems that for 6 and 7 los recovery is needed. I already had it on my phone and it flashed the correct rom but, in hindsight, that was bad testing procedure. I’ll try to add LOS recovery support to this.

**Comment by anon1892** [comment]
>  I’ll try to add LOS recovery support to this.

Does LOS recovery support "adb shell twrp..." commands ?
If yes, please wait a while, I'm working on how OAI handle recoveries (I'm adding OrangeFox support, see #188 )
After I commit all my changes, it should be very simple (I hope ^^)

**Comment by tsterbak** [comment]
> Does LOS recovery support "adb shell twrp..." commands ?

That is actually the issue... I suspect there is some scripting possible, but I found it documented nowhere and was not able to use it yet.

This is the source file of the LOS recovery (as far as I understand it): https://github.com/LineageOS/android_bootable_recovery/blob/lineage-20.0/recovery.cpp

**Comment by anon1892** [comment]
In the worst case, we can make some more steps for the user : 
The Lineage recovery UI is very simple, so something like "Click on advenced, then adb sideload" shouldn't be too complicated for the average user

Let's see how it works, there may be solutions to this problem : https://doc.e.foundation/easy-installer

**Pull request closed without merging**
