### PR TITLE
Reworked the device request template as form

### PR DESCRIPTION
**Pull request by MagicLike**

### CODE REVIEW

**Comment by tsterbak** [comment]
Hey, thank you for building this! :slightly_smiling_face: 

It can only be merged with the next release of the Installer, since the issue template URL is part of the source code (https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/views/start_view.py#L275)

**Comment by MagicLike** [comment]
> Hey, thank you for building this! :slightly_smiling_face: 
> 
> It can only be merged with the next release of the Installer, since the issue template URL is part of the source code (https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/views/start_view.py#L275).
> 
> Can you update the URL and make sure, that the new template works with the new URL?

Oh yeah totally forgot about that one - either I can test that tonight or tomorrow afternoon! 👍

**Comment by MagicLike** [comment]
@tsterbak Updated the URL and tested it, should work just fine :heavy_check_mark:

**Comment by MagicLike** [comment]
@tsterbak should I add the "`" to the device code variable in the issue link, that the device code gets formatted like this?
grafik

**Comment by tsterbak** [comment]
> should I add the "`" to the device code variable in the issue link, that the device code gets formatted like this?

Yeah, that looks neat! :)

**Comment by MagicLike** [comment]
> > should I add the "`" to the device code variable in the issue link, that the device code gets formatted like this?
> 
> Yeah, that looks neat! :)

Done! https://github.com/openandroidinstaller-dev/openandroidinstaller/commit/0bc2f9dc0c3183e7b4190b9e64e0159ad22a1771

**Pull request merged**
