### PR TITLE
Improve resizing/scaling support

### PR DESCRIPTION
**Pull request by tsterbak**
Now the right size of the installer scales with the screen when resizing.

### CODE REVIEW

**Comment by tsterbak** [comment]
@SirRGB please have a look if that fixes your issue :)

**Review by MagicLike — APPROVED** [review]
LGTM (I guess :D)

**Comment by SirRGB** [comment]
very nice, but there still is cut off text

https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/views/start_view.py#L117

grafik

**Comment by tsterbak** [comment]
I hope I resolved it now :) Let me know if something else is missing.

**Pull request merged**
