### PR TITLE
add Samsung S4 mini (serranolte)

### PR DESCRIPTION
**Pull request by freechelmi**
serranolte and serranoltexx supported

### CODE REVIEW

**Comment by tsterbak** [comment]
Looks good! :) Could you add the device also to the README?

**Comment by tsterbak** [comment]
Do you think it would also be save to support other S4 mini variants with this config?
For example: https://wiki.lineageos.org/devices/serrano3gxx/ or https://wiki.lineageos.org/devices/serranodsdd/

**Comment by freechelmi** [comment]
Readme for serranoltexx added , I'm not sure about 3G variants , we can test and add them later on

**Comment by MagicLike** [comment]
@tsterbak Are two configs for the same device codes necessary?

**Review by MagicLike — CHANGES_REQUESTED** [review]
Please remove the trailing slash at the end of the wiki link. All the others will be removed when #129 gets merged...

**Comment by freechelmi** [comment]
Done , Yes if you can resolve the conflict :-)

**Comment by MagicLike** [comment]
> Done , Yes if you can resolve the conflict :-)

One thing: please remove the trailing slash as stated in my review. Would it also be possible to move every text of `content` into its own line using the `>` as shown in line 13 of your config to ensure consistency?

**Pull request merged**
