### PR TITLE
add mi439 twrp name

### PR DESCRIPTION
**Pull request by SirRGB**
Should partially fix https://github.com/openandroidinstaller-dev/openandroidinstaller/issues/352

### CODE REVIEW

**Comment by SirRGB** [comment]
Might need to edit the config to not recommend ofox...

**Comment by anon1892** [comment]
At the beginning, I started to support Xiaomi devices in OAI with OrangeFox, but OFox addition to OAI is delayed to v0.6 or maybe more. For some devices, only OFox is available (it was created at the beginning for Xiaomi devices), and it's more user-friendly I think.

But it can be removed for now, you're right.

**Comment by SirRGB** [comment]
Might be more userfriendly to point the user to a direct twrp download link for now. U can change it once ofox is supported ig.

**Comment by anon1892** [comment]
What do you mean by alias support?

**Comment by SirRGB** [comment]
"twrp-link: mi439"
Should create a valid twrp download link in the installer iirc.
I tought ofox for mi439 was official too.

**Pull request merged**
