### PR TITLE
add griffin and cheesedump support

### PR DESCRIPTION
**Pull request by SirRGB**
* copy pasta from cedric and guacamole

### CODE REVIEW

**Comment by SirRGB** [comment]
tested griffin carbonrom and cheeseburger crdroid
flashed twrp/rom on already unlocked bootloader

**Comment by tsterbak** [comment]
Hey, thank you for your work! This will be added in the next release :slightly_smiling_face: 

One quick question, did the naming convention of the config files and device code work for you for the OnePlus devices?
I found it a bit annoying and confusing so far, and for the OnePlus devices I added, I actually hardcoded a mapping (e.g. OnePlus6 to guacamole and back) to keep the file name the device code. But if the approach you took worked fine for you, I might remove the mapping and adapt to your approach. How was your experience? :slightly_smiling_face:

**Comment by SirRGB** [comment]
Well I just used the app when trying to bringup the device and it didnt work when the file was named after the codename and said "unknown device: OnePlus5" so I just went for that and it worked. Im guessing with the 5T name tho, but it would fit the naming convention.

**Review by tsterbak — APPROVED** [review]
Looks good. This will go in the next release

**Pull request merged**
